# Generated by Django 4.2.2 on 2023-06-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEvento', models.CharField(max_length=30)),
                ('descripcionEvento', models.TextField(max_length=150)),
                ('fechaInicioEvento', models.DateField()),
                ('fechaFinEvento', models.DateField()),
                ('horaInicioEvento', models.TimeField()),
                ('horaFinEvento', models.TimeField()),
                ('lugarEvento', models.TextField()),
                ('fotoPromoEvento', models.TextField()),
                ('capacidadGeneral', models.IntegerField()),
                ('capacidadVip', models.IntegerField()),
                ('capacidadSuperVip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBoleta', models.CharField(max_length=50)),
                ('tipoBoleta', models.CharField(max_length=15)),
                ('precioBoleta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('beneficiosBoleta', models.TextField()),
                ('estadoBoleta', models.CharField(max_length=15)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventosApiapp.evento')),
            ],
        ),
    ]
